/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module dln_cmp2(x0, x1, x2, x3, y0);
  wire _0_;
  wire _1_;
  input x0;
  wire x0;
  input x1;
  wire x1;
  input x2;
  wire x2;
  input x3;
  wire x3;
  output y0;
  wire y0;
  assign _0_ = x2 ^ x0;
  assign _1_ = x3 ^ x1;
  assign y0 = ~(_0_ | _1_);
endmodule
