/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module dln_neg2(x0, x1, y0, y1, y2);
  wire _0_;
  input x0;
  wire x0;
  input x1;
  wire x1;
  output y0;
  wire y0;
  output y1;
  wire y1;
  output y2;
  wire y2;
  assign _0_ = ~(x0 | x1);
  assign y2 = ~_0_;
  assign y1 = x0 ^ x1;
  assign y0 = x0;
endmodule
