/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module dln_sel_mux2(x0, x1, x2, x3, y0);
  input x0;
  wire x0;
  input x1;
  wire x1;
  input x2;
  wire x2;
  input x3;
  wire x3;
  output y0;
  wire y0;
  assign y0 = x3 ? x1 : x0;
endmodule
