/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module dln_max2(x0, x1, x2, x3, y0, y1);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  input x0;
  wire x0;
  input x1;
  wire x1;
  input x2;
  wire x2;
  input x3;
  wire x3;
  output y0;
  wire y0;
  output y1;
  wire y1;
  assign _02_ = ~x3;
  assign _03_ = ~x1;
  assign _04_ = ~(x3 | x1);
  assign y1 = ~_04_;
  assign _00_ = ~((x3 | _03_) & x2);
  assign _01_ = ~((_02_ | x1) & x0);
  assign y0 = ~(_00_ & _01_);
endmodule
