/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module dln_div2(x0, x1, x2, x3, y0, y1);
  wire _0_;
  wire _1_;
  input x0;
  wire x0;
  input x1;
  wire x1;
  input x2;
  wire x2;
  input x3;
  wire x3;
  output y0;
  wire y0;
  output y1;
  wire y1;
  assign _0_ = ~x0;
  assign _1_ = ~x1;
  assign y0 = ~((x2 & _0_) | (_1_ & x3));
  assign y1 = ~((x2 & _1_) | x3);
endmodule
