/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module dln_mul2(x0, x1, x2, x3, y0, y1, y2, y3);
  wire _0_;
  wire _1_;
  wire _2_;
  input x0;
  wire x0;
  input x1;
  wire x1;
  input x2;
  wire x2;
  input x3;
  wire x3;
  output y0;
  wire y0;
  output y1;
  wire y1;
  output y2;
  wire y2;
  output y3;
  wire y3;
  assign _2_ = ~(x2 & x0);
  assign y0 = ~_2_;
  assign _0_ = ~(x1 & x3);
  assign y3 = ~(_2_ | _0_);
  assign y2 = ~(y0 | _0_);
  assign _1_ = ~((x2 & x1) | (x3 & x0));
  assign y1 = ~(y3 | _1_);
endmodule
