/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module dln_add2(x0, x1, x2, x3, y0, y1, y2);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  input x0;
  wire x0;
  input x1;
  wire x1;
  input x2;
  wire x2;
  input x3;
  wire x3;
  output y0;
  wire y0;
  output y1;
  wire y1;
  output y2;
  wire y2;
  assign _02_ = ~(x3 | x1);
  assign _03_ = ~(x2 & x0);
  assign _00_ = ~(x3 & x1);
  assign y2 = ~((_03_ & _00_) | _02_);
  assign y0 = x2 ^ x0;
  assign _01_ = x3 ^ x1;
  assign y1 = ~(_03_ ^ _01_);
endmodule
