/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module dln_sub2(x0, x1, x2, x3, y0, y1, y2);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  input x0;
  wire x0;
  input x1;
  wire x1;
  input x2;
  wire x2;
  input x3;
  wire x3;
  output y0;
  wire y0;
  output y1;
  wire y1;
  output y2;
  wire y2;
  assign _06_ = ~x2;
  assign _07_ = ~x1;
  assign _00_ = ~x0;
  assign _01_ = ~(_07_ & x3);
  assign _02_ = ~(_07_ | x3);
  assign _03_ = ~(x2 & _00_);
  assign y2 = ~((_02_ | _03_) & _01_);
  assign _04_ = ~(_06_ & x0);
  assign y0 = ~(_03_ & _04_);
  assign _05_ = x1 ^ x3;
  assign y1 = ~(_03_ ^ _05_);
endmodule
