/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module dln_abs2(x0, x1, y0, y1);
  input x0;
  wire x0;
  input x1;
  wire x1;
  output y0;
  wire y0;
  output y1;
  wire y1;
  assign y0 = x0;
  assign y1 = x1;
endmodule
