/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module dln_sqr2(x0, x1, y0, y1, y2, y3);
  wire _0_;
  wire _1_;
  input x0;
  wire x0;
  input x1;
  wire x1;
  output y0;
  wire y0;
  output y1;
  wire y1;
  output y2;
  wire y2;
  output y3;
  wire y3;
  assign _0_ = ~x1;
  assign y2 = ~(x0 | _0_);
  assign _1_ = ~(x0 & x1);
  assign y3 = ~_1_;
  assign y0 = x0;
  assign y1 = 1'h0;
endmodule
